manifests/0000_05_config-operator_01_image.crd.yaml

This should reduce flakes on cluster-image-registry-operator CI.

Add the status subresource to the image config

---

Dockerfile
Dockerfile.rhel7

this may solve the issue from https://github.com/openshift/installer/pull/1187
/assign @mfojtik

create bootstrap-manifests directory

---

manifests/0000_05_config-operator_01_scheduling.crd.yaml

@deads2k @ravisantoshgudimetla @derekwaynecarr 
mirrors `Scheduler` type in https://github.com/openshift/api/blob/master/config/v1/types_scheduling.go

Add Scheduler CRD

---

manifests/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml

Missing this means openshift controller manager can't update status for cluster resource quota 🤦‍♂️

crq: add status sub-resource

---

manifests/0000_05_config-operator_02_config.clusterrole.yaml

Adds a read permission for the cluster-reader-aggregate role for config.openshift.io objects.
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1697638
Old PR: https://github.com/openshift/origin/pull/22533

rbac: add aggregate-to-cluster-reader permissions

---

manifests/0000_03_authorization-openshift_01_rolebindingrestriction.crd.yaml

This validation is good, at least I was able to create a RBR in my test cluster that had the old CRD (before the revert)

Add RoleBindingRestriction CRD

---

manifests/0000_10_config-operator_01_apiserver.crd.yaml
manifests/0000_10_config-operator_01_build.crd.yaml
manifests/0000_10_config-operator_01_dns.crd.yaml
manifests/0000_10_config-operator_01_featuregate.crd.yaml
manifests/0000_10_config-operator_01_ingress.crd.yaml
manifests/0000_10_config-operator_01_project.crd.yaml
manifests/0000_10_config-operator_01_scheduler.crd.yaml

Some config resources have status without any values yet.  This makes sure we have separate endpoints before anything slips in.  I think our only remaining difficulty is infrastructure and networking.

specify status subresources for resources with empty status

---

Dockerfile
Dockerfile.rhel7
Makefile

Need review on the image target, note that the name changes to match the examples in https://github.com/openshift/cluster-config-operator/pull/88

Bump to golang 1.12 and update Makefile image target

---

manifests/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml
manifests/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml-merge-patch

Like https://github.com/openshift/cluster-config-operator/pull/91, but for master.
Working around https://github.com/kubernetes-sigs/controller-tools/issues/328.
cc @damemi – this is another patch we need to port when using the controller-tools generator.

ClusterResourceQuota: allow integer values

---

Dockerfile
Dockerfile.rhel7

Image builds are failing with:
```
magebuilder build has begun; waiting for it to finish
--> FROM sha256:d721c86058dea92fcde74487fdf26c4c8a56224c996f9bb75f4c3845011d592f as builder
--> ADD atomic-reactor-repos/* '/etc/yum.repos.d/'
--> USER root
--> RUN mv -f /etc/yum.repos.d/ubi.repo /tmp || :
--> USER 0
--> ENV SOURCE_GIT_COMMIT=ad3efbbd55cbc6f7348f6845ae6d62ed75ee4159 SOURCE_DATE_EPOCH=1569873526 BUILD_VERSION=v4.3.0 SOURCE_GIT_URL=https://github.com/openshift/cluster-config-operator SOURCE_GIT_TAG=v0.0.0-alpha.0-170-gad3efbbd BUILD_RELEASE=201909302346
--> WORKDIR /go/src/github.com/openshift/cluster-config-operator
--> COPY . .
--> ENV GO_PACKAGE github.com/openshift/cluster-config-operator
--> RUN go build -ldflags "-X $GO_PACKAGE/pkg/version.versionFromGit=$(git describe --long …
```

Enable TLS1.3 for go build

---

Makefile
manifests/0000_10_config-operator_01_consoleclidownload.crd.yaml
manifests/0000_10_config-operator_01_consoleexternalloglink.crd.yaml
manifests/0000_10_config-operator_01_consolelink.crd.yaml
manifests/0000_10_config-operator_01_consolenotification.crd.yaml

See https://github.com/openshift/console-operator/pull/302 for associated removal PR.  These files have existed in the console-operator, but should live here.
This is not a 1:1, however, due to `update-codegen-crds` modifying the files.
@spadgett @rhamilto @jhadvig fyi.
The `codegen` command overwrites these files based on what is in `openshift/api`, so what we previously had documented may no longer be here (if it was also not in `openshift/api`)

Migrate console extensions CRDs from console-operator

---

Makefile

This allows passing a custom image registry to `make images`, like so:
`make IMAGE_REGISTRY=quay.io/sallyom images`

Makefile allow passing image tag to 'make images'

---

manifests/0000_30_config-operator_02_service.yaml
manifests/0000_30_config-operator_03_servicemonitor.yaml

Without this fix the prometheus won't see the config operator metrics endpoint and the target will be down.

manifests: fix metrics labels

---

pkg/operator/kube_cloud_config/aws.go
pkg/operator/kube_cloud_config/aws_test.go
pkg/operator/kube_cloud_config/controller.go
pkg/operator/kube_cloud_config/controller_test.go

The infrastructure.config.openshift.io/v1 requires that the key for cloud config in the generated config map be `cloud.conf`.
Previously the controller was just copying and not enforcing the target key.
no both the as-is and aws transformers enforce this, and also the tests were updated to check that.

Bug 1825944: kube_cloud_config: enforce the target key in config map to cloud.conf

---

pkg/operator/kube_cloud_config/controller.go

Only send event when we actually delete the config map.

Fix event spam in kube cloud config

---

pkg/operator/kube_cloud_config/azure.go
pkg/operator/kube_cloud_config/azure_test.go
pkg/operator/kube_cloud_config/controller.go
pkg/operator/kube_cloud_config/controller_test.go

Populate the `cloud` field in kube cloud.conf stored in the kube-cloud-config ConfigMap in the openshift-config-managed namespace. This field informs in which Azure cloud environment the cluster is installed and consequently which Azure API endpoint should be used when  communicating via the Azure SDK.
The value populated comes from the `.status.platformStatus.azure.cloudName` field of the infrastructure.config.openshift.io resource. If the field is empty or missing, then the default "AZUREPUBLICCLOUD" value is set for the `cloud` field in the kube cloud config. If the field generated from the infrastructure resource conflicts with the field in the user-provided kube
cloud config, then the controller will error on syncing the infrastructure resource.
See openshift/enhancements#321 …

kube_cloud_config: support for other Azure cloud environments

---

pkg/operator/aws_platform_service_location/controller.go
pkg/operator/aws_platform_service_location/controller_test.go

Previously when the user would reset the service endpoints in the spec, the controller would exit early as no work needed to be done.
That means it would leave the status set with previous service endpoints.
Now the controller resets the service endpoints when the user set the service endpoints to empty.

Bug 1850681: aws_platform_service_location: resync when user unsets the service endpoints in spec

---

pkg/cmd/render/render.go
pkg/operator/kube_cloud_config/aws.go
pkg/operator/kube_cloud_config/aws_test.go
pkg/operator/kube_cloud_config/azure.go
pkg/operator/kube_cloud_config/azure_test.go
pkg/operator/kube_cloud_config/bootstrap.go
pkg/operator/kube_cloud_config/controller.go
pkg/operator/kube_cloud_config/controller_test.go
pkg/operator/kube_cloud_config/doc.go
pkg/operator/starter.go

This relies on https://github.com/openshift/cluster-config-operator/pull/133 and is included for now. When it can be shown that it works, I can remove those commits from this PR. This is very much a WIP, so please point out anywhere that I am going about things completely wrong ;-)
https://issues.redhat.com/browse/CORS-1458

render: generate cloud config when infrastructure and configmap are provided

---

empty-resources/0000_05_config-operator_02_apiserver.cr.yaml

Final PR to activate deep oauth token audit logging from https://github.com/openshift/library-go/pull/894 for new 4.6 clusters.
Compare:
- https://github.com/openshift/cluster-openshift-apiserver-operator/pull/392
- https://github.com/openshift/cluster-authentication-operator/pull/324

Bug 1878648: oauth: audit log oauthaccesstokens if fresh 4.6 install

---

manifests/0000_10_config-operator_01_openshift-config-managed-ns.yaml
manifests/0000_10_config-operator_01_openshift-config-ns.yaml
manifests/0000_10_config-operator_02_config.clusterrole.yaml
manifests/0000_30_config-operator_00_namespace.yaml
manifests/0000_30_config-operator_01_operator.cr.yaml
manifests/0000_30_config-operator_01_prometheusrole.yaml
manifests/0000_30_config-operator_02_prometheusrolebinding.yaml
manifests/0000_30_config-operator_02_service.yaml
manifests/0000_30_config-operator_03_servicemonitor.yaml
manifests/0000_30_config-operator_04_roles.yaml
manifests/0000_30_config-operator_05_serviceaccount.yaml
manifests/0000_30_config-operator_07_deployment.yaml
manifests/0000_30_config-operator_08_clusteroperator.yaml

This is matches https://github.com/openshift/enhancements/pull/414 and doesn't change existing behavior

bug 1871890: add current profile annotations to CVO manifests

---

pkg/operator/aws_platform_service_location/controller.go
pkg/operator/secureaccesstoken/controller.go
pkg/operator/starter.go

The annotation oauth-apiserver.openshift.io/secure-token-storage: true set on the config/v1 apiserver object make openshift-apiserver deeply log oauth tokens, noth access and authorize (if openshift-apiserver is responsible for this; in fresh 4.6 install it is not, but oauth-apiserver is).
This requires that there are no non-sha256 tokens in the system. For 4.6 installs this is guaranteed.
This PR adds a controller to remove the "oauth-apiserver.openshift.io/secure-token-storage" annotation from the APIServer config/v1 object after a potential downgrade from 4.6, to allow for the fact that non-sha256 are created on 4.5.
Counterpart to 4.6 PRs:
- https://github.com/openshift/library-go/pull/894 (merged already)
- https://github.com/openshift/cluster-openshift-apiserver-operator/pull/392
- …

Bug 1879492: Add secure access token annotation controller to handle downgrade from 4.6

---

pkg/operator/operatorloglevel/loglevel_controller.go

This PR adds the missing service ca operator resource to the list of resources used by log level controller.

Bug 1883898: add service ca operator to log level controller resource list

---

empty-resources/0000_05_config-operator_02_apiserver.cr.yaml
empty-resources/0000_05_config-operator_02_authentication.cr.yaml
empty-resources/0000_05_config-operator_02_build.cr.yaml
empty-resources/0000_05_config-operator_02_console.cr.yaml
empty-resources/0000_05_config-operator_02_dns.cr.yaml
empty-resources/0000_05_config-operator_02_featuregate.cr.yaml
empty-resources/0000_05_config-operator_02_image.cr.yaml
empty-resources/0000_05_config-operator_02_infrastructure.cr.yaml
empty-resources/0000_05_config-operator_02_ingress.cr.yaml
empty-resources/0000_05_config-operator_02_network.cr.yaml
empty-resources/0000_05_config-operator_02_oauth.cr.yaml
empty-resources/0000_05_config-operator_02_operatorhub.cr.yaml
empty-resources/0000_05_config-operator_02_project.cr.yaml
empty-resources/0000_05_config-operator_02_proxy.cr.yaml
empty-resources/0000_05_config-operator_02_scheduler.cr.yaml
manifests/0000_10_config-operator_01_openshift-config-managed-ns.yaml
manifests/0000_10_config-operator_01_openshift-config-ns.yaml
manifests/0000_10_config-operator_02_config.clusterrole.yaml
manifests/0000_30_config-operator_00_namespace.yaml
manifests/0000_30_config-operator_01_operator.cr.yaml
manifests/0000_30_config-operator_01_prometheusrole.yaml
manifests/0000_30_config-operator_02_prometheusrolebinding.yaml
manifests/0000_30_config-operator_02_service.yaml
manifests/0000_30_config-operator_03_servicemonitor.yaml
manifests/0000_30_config-operator_04_roles.yaml
manifests/0000_30_config-operator_05_serviceaccount.yaml
manifests/0000_30_config-operator_07_deployment.yaml
manifests/0000_30_config-operator_08_clusteroperator.yaml

This partially implements phase 1 of https://github.com/openshift/enhancements#482
and does not change behavior. Initially, all cluster-config-operator
manifests are included in the single-node-developer cluster profile.
Follow-on PRs may exclude any of these that are not needed in the
profile.

Bug 1915473: Annotate manifests for single-node-developer cluster profile

---

manifests/0000_30_config-operator_07_deployment.yaml

The config operator runs cluster-critical controllers.
Addressing https://github.com/openshift/origin/pull/25931.

Mark operator pod as system-cluster-critical

---

pkg/operator/kube_cloud_config/doc.go

The typo is from a854f43ce1 (#120).

pkg/operator/kube_cloud_config: Fix "kuberneted" -> "Kubernetes" doc typo

---

empty-resources/0000_05_config-operator_02_apiserver.cr.yaml
empty-resources/0000_05_config-operator_02_authentication.cr.yaml
empty-resources/0000_05_config-operator_02_build.cr.yaml
empty-resources/0000_05_config-operator_02_console.cr.yaml
empty-resources/0000_05_config-operator_02_dns.cr.yaml
empty-resources/0000_05_config-operator_02_featuregate.cr.yaml
empty-resources/0000_05_config-operator_02_image.cr.yaml
empty-resources/0000_05_config-operator_02_infrastructure.cr.yaml
empty-resources/0000_05_config-operator_02_ingress.cr.yaml
empty-resources/0000_05_config-operator_02_network.cr.yaml
empty-resources/0000_05_config-operator_02_oauth.cr.yaml
empty-resources/0000_05_config-operator_02_operatorhub.cr.yaml
empty-resources/0000_05_config-operator_02_project.cr.yaml
empty-resources/0000_05_config-operator_02_proxy.cr.yaml
empty-resources/0000_05_config-operator_02_scheduler.cr.yaml
manifests/0000_10_config-operator_01_openshift-config-managed-ns.yaml
manifests/0000_10_config-operator_01_openshift-config-ns.yaml
manifests/0000_10_config-operator_02_config.clusterrole.yaml
manifests/0000_30_config-operator_00_namespace.yaml
manifests/0000_30_config-operator_01_operator.cr.yaml
manifests/0000_30_config-operator_01_prometheusrole.yaml
manifests/0000_30_config-operator_02_prometheusrolebinding.yaml
manifests/0000_30_config-operator_02_service.yaml
manifests/0000_30_config-operator_03_servicemonitor.yaml
manifests/0000_30_config-operator_04_roles.yaml
manifests/0000_30_config-operator_05_serviceaccount.yaml

This matches https://github.com/openshift/enhancements/pull/445 and does not change behavior.
- Bump github.com/openshift/api (needed to include https://github.com/openshift/api/pull/781)
- Add IBM Cloud managed annotations to CVO manifests

Add IBM Cloud managed annotations to CVO manifests

---

manifests/0000_50_config-operator_09_user-priority-class.yaml

Add user facing critical priority class to CCO. This priority class is currently in [CMO](https://github.com/openshift/cluster-monitoring-operator/blob/master/manifests/0000_50_cluster-monitoring-operator_00_0user-priority-class.yaml), however we see that it is beneficial enough to be used by multiple entities like RHOAM, so moving it CCO.
cc @smarterclayton

Bug 1949145: Add user facing priority class

---

manifests/0000_50_config-operator_09_user-priority-class.yaml

As part of #191, I missed adding required annotations to priority class manifest. Adding them now.
cc @soltysh

Bug 1949145: Add missing annotations to upc

---

manifests/0000_30_config-operator_00_namespace.yaml
manifests/0000_30_config-operator_07_deployment.yaml

In support of the workload partitioning feature
(openshift/enhancements#703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

Add management workload annotations

---

manifests/0000_30_config-operator_07_deployment.yaml

As per openshift/enhancements#739, the workload annotations names are changing.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
/hold
Hold until after openshift/kubernetes#632 is merged

Rename workload annotations

---

manifests/0000_50_config-operator_09_user-priority-class.yaml

CVO hotloops on this manifest, applying preemptionPolicy post-install.
Found during hotloop verbose testing in CVO - https://github.com/openshift/cluster-version-operator/pull/561 ([log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/561/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic/1392749307458752512/artifacts/e2e-agnostic/gather-extra/artifacts/pods/openshift-cluster-version_cluster-version-operator-9bc9644c5-tgd95_cluster-version-operator.log))

Bug 1960339: manifests: add preemptionPolicy for openshift-user-critical

---

manifests/0000_50_config-operator_09_user-priority-class.yaml

This property doesn't render in the final object, so CVO hotloops attempting to set it.
Follow-up for https://github.com/openshift/cluster-config-operator/pull/202.
Verified that its no longer hotlooping via `test e2e openshift/cluster-version-operator#561,openshift/cluster-config-operator#205 aws` task in cluster-bot:
```
$ curl -sL https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws/1400081719066890240/artifacts/launch/pods/openshift-cluster-version_cluster-version-operator-55b7ff6f99-5pz7v_cluster-version-operator.log | grep -oP "Updating \K.+ due to diff" | cut -d' ' -f1 | sort | uniq -c
14 ClusterServiceVersion
447 Deployment
```

Bug 1960339: openshift-user-critical: unset globalDefault

---

manifests/0000_50_config-operator_09_user-priority-class.yaml

Adds missing include annotation in the user-priority-class manifest.

Add missing include annotation for ibm-cloud-managed

---

manifests/0000_30_config-operator_07_deployment.yaml

Starting from OpenShift 4.11 pod security admission is being activated. In OpenShift the default pod security admission level is going to be `restricted`. This PR fixes workloads from this repository. Concretely, the following violations have been detected:
```
{
  "objectRef": "openshift-config-operator/deployments/openshift-config-operator",
  "pod-security.kubernetes.io/audit-violations": "would violate PodSecurity \"restricted:latest\": allowPrivilegeEscalation != false (container \"openshift-config-operator\" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container \"openshift-config-operator\" must set securityContext.capabilities.drop=[\"ALL\"]), runAsNonRoot != true (pod or container \"openshift-config-operator\" must set …
```

manifests/deployment: comply to restricted pod security level

---

go.mod
go.sum
vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
vendor/github.com/openshift/api/config/v1/types_ingress.go
vendor/modules.txt

Backport commit 019a246c52 to bump api in release-4.9 for https://bugzilla.redhat.com/show_bug.cgi?id=2075551

Bug 2075551: [release-4.9] backport api to commit 019a246c52

---

README.md

This repo has no owner.  We should not add additional code here.
Ultimately, most of the "one time migration code" actually lives for quite a while and deserves a home more closely associated with what it does.  Remember that our config.openshift.io resources are based on how cluster-admins associate them, not based on the operators (often plural) that actually handle the information.  This means that we can easily end up in situations where individual fields of the same resources are set by different operators.

This is not the repo you're looking for.

---

manifests/0000_30_config-operator_01_operator.cr.yaml

Related to [TRT-567](https://issues.redhat.com//browse/TRT-567)
Blocker Jira to remove this [TRT-570](https://issues.redhat.com/browse/TRT-570)
We'd like to turn on more verbose logging to track readiness probe errors that get timeouts.  We consider this temporary and intend to remove this once we get enough data.

Increase verbosity level to track probe timeouts

---

pkg/operator/featuregates/featuregate_controller.go
pkg/operator/featuregates/featuregate_controller_test.go

This will allow panic-ing on unknown featuregates in consumer code.  CustomNoUpgrade becomes even harder because it must specify everything, but it's always been hard.
/assign @JoelSpeed

specify all known featureGates in disabled

---

go.mod
go.sum
pkg/cmd/render/render.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/featuregate.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/hardcoded_featuregate_reader.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/simple_featuregate_reader.go
vendor/github.com/openshift/library-go/pkg/operator/render/options/config.go
vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
vendor/modules.txt

adds a check for those consuming rendered manifests that none of the contents conflict.  Conflicts would result in unpredictable results on the cluster.

Require consistency in rendered artifacts

---

pkg/operator/removelatencysensitive/OWNERS
pkg/operator/removelatencysensitive/removelatencysensitive_controller.go
pkg/operator/removelatencysensitive/removelatencysensitive_controller_test.go
pkg/operator/starter.go

This let's us avoid dead-ending clusters.

stomp the latencysensitive featureset for equivalent default

---

pkg/operator/featureupgradablecontroller/OWNERS
pkg/operator/featureupgradablecontroller/feature_upgradeable_controller.go
pkg/operator/featureupgradablecontroller/feature_upgradeable_controller_test.go
pkg/operator/removelatencysensitive/OWNERS
pkg/operator/removelatencysensitive/removelatencysensitive_controller.go
pkg/operator/removelatencysensitive/removelatencysensitive_controller_test.go
pkg/operator/starter.go

For multiple years this has been the equivalent of "".  Make these consistent because in 4.13 the featureset handling added to the CVO didn't account for this and its unnecessary.  It's more practical to migrate a few existing clusters than modify all producers.

OCPBUGS-16164: retire LatencySensitive featureset

---

go.mod
go.sum
vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
vendor/github.com/openshift/api/config/v1/types_infrastructure.go
vendor/modules.txt

PR is for updating the openshift/api package to the latest version which contains the API changes(https://github.com/openshift/api/pull/1630) having the fix for https://issues.redhat.com/browse/OCPBUGS-21653
Package updated using command
`go get github.com/openshift/api@release-4.14`

[release-4.14] OCPBUGS-21653: Update openshift/api package to latest version

---

Dockerfile.rhel7

/hold
must merge together with https://github.com/openshift/api/pull/1666
While the vendored level in cluster-config-operator matches, these can show green simultaneously.  When that happens, we need to manually merge both to avoid future conflicts.

yield CRDs and empty resource rendering to api imge

---

Dockerfile.rhel7
empty-resources/0000_05_config-operator_02_apiserver.cr.yaml
empty-resources/0000_05_config-operator_02_authentication.cr.yaml
empty-resources/0000_05_config-operator_02_console.cr.yaml
empty-resources/0000_05_config-operator_02_dns.cr.yaml
empty-resources/0000_05_config-operator_02_featuregate.cr.yaml
empty-resources/0000_05_config-operator_02_image.cr.yaml
empty-resources/0000_05_config-operator_02_infrastructure.cr.yaml
empty-resources/0000_05_config-operator_02_ingress.cr.yaml
empty-resources/0000_05_config-operator_02_network.cr.yaml
empty-resources/0000_05_config-operator_02_oauth.cr.yaml
empty-resources/0000_05_config-operator_02_project.cr.yaml
empty-resources/0000_05_config-operator_02_proxy.cr.yaml
empty-resources/0000_05_config-operator_02_scheduler.cr.yaml
empty-resources/0000_10_config-operator_02_node.cr.yaml

Reverts openshift/cluster-config-operator#392
Hypershift CI relies on these files and is the removal of these files is causing a CI failure.

Revert "OCPBUGS-26541: remove duplicate manifests in image"

---

manifests/0000_10_config-operator_01_openshift-config-ns.yaml

This PR sets the required PSa labels for the `openshift-config` namespace.
Namespaces that don't define PSa labels currently get `restricted` by default; this results in violations from workloads that run in the `openshift-config` namespace, as this is a runlevel 0 namespace and likely these payloads need privileged policy.
See https://issues.redhat.com/browse/AUTH-262 for more information.

OCPBUGS-28621: Add required PSa labels

---

manifests/0000_10_config-operator_07_deployment.yaml

[OCPBUGS-36151](https://issues.redhat.com/browse/OCPBUGS-36151)
Manual cherry-pick of #410

[release-4.15] OCPBUGS-36151: Set required-scc for openshift workloads

---

.ci-operator.yaml
Dockerfile.rhel7
go.mod

Continuation of #429 which has not updated the go.mod to 1.23, and therefore is failing to verify

OCPBUGS-45477: Updating ose-cluster-config-operator-container image to be consistent with ART for 4.19

---

pkg/operator/featuregates/featuregate_controller.go
pkg/operator/featuregates/featuregate_controller_test.go

In OCPBUGS-57187 it was identified that setting only the `.spec.featureSet` field to `CustomNoUpgrade` and not configuring a value for the `.spec.customNoUpgrade` field in the `FeatureGate` API resulted in an empty enabled/disabled set of feature gates, leading to panics in various platform operators.
This PR ensures that even in this edge case, we always fill the list of enabled/disabled feature gates with the default set.
It also adds a unit test to capture this scenario.

OCPBUGS-57187: featuregates: always complete featuregates when feature set is CustomNoUpgrade
