manifests/0000_05_config-operator_01_infrastructure.crd.yaml
manifests/0000_05_config-operator_01_network.crd.yaml
manifests/0000_05_config-operator_01_openshift-config-managed-ns.yaml
manifests/0000_05_config-operator_01_openshift-config-ns.yaml

Adds namespaces for config and infrastructures and networks.

add more cluster-config resources

---

manifests/0000_05_config-operator_01_apiserver.crd.yaml
manifests/0000_05_config-operator_01_build.crd.yaml
manifests/0000_05_config-operator_01_features.crd.yaml
manifests/0000_05_config-operator_01_image.crd.yaml

We need types for APIServer and Features.
/assign @mfojtik

add new config.openshift.io types

---

manifests/0000_05_config-operator_01_project.crd.yaml

add project config crd

---

manifests/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml

depends on https://github.com/openshift/origin/pull/22277
/hold

add cluster resource quota resources

---

empty-resources/0000_05_config-operator_02_image.cr.yaml
empty-resources/0000_05_config-operator_02_infrastructure.cr.yaml

from https://github.com/openshift/cluster-config-operator/pull/35

add empty CRs

---

empty-resources/0000_05_config-operator_02_apiserver.cr.yaml
empty-resources/0000_05_config-operator_02_authentication.cr.yaml
empty-resources/0000_05_config-operator_02_build.cr.yaml
empty-resources/0000_05_config-operator_02_console.cr.yaml

alternative to https://github.com/openshift/cluster-config-operator/pull/42

remove possibly failing CRs

---

empty-resources/0000_05_config-operator_02_apiserver.cr.yaml
empty-resources/0000_05_config-operator_02_authentication.cr.yaml
empty-resources/0000_05_config-operator_02_build.cr.yaml
empty-resources/0000_05_config-operator_02_console.cr.yaml

Signed-off-by: Monis Khan <mkhan@redhat.com>
Requires https://github.com/openshift/cluster-kube-apiserver-operator/pull/399
@openshift/sig-auth @openshift/sig-master

Add back all empty custom resources (including authentication)

---

manifests/0000_03_security-openshift_01_scc.crd.yaml
vendor/github.com/openshift/api/security/v1/types.go

TEST PR DO NOT MERGE

---

glide.lock
manifests/0000_03_authorization-openshift_01_rolebindingrestriction.crd.yaml
vendor/github.com/openshift/api/authorization/v1/generated.proto
vendor/github.com/openshift/api/authorization/v1/types.go
vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_cmd.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
vendor/golang.org/x/tools/go/analysis/analysis.go
vendor/golang.org/x/tools/go/analysis/internal/checker/checker.go
vendor/golang.org/x/tools/internal/span/span.go

@deads2k 
Same as [this](https://github.com/openshift/cluster-config-operator/pull/59), with a proper bump.

Bump for RBR CRD, add nullables, Namespaced

---

OWNERS

@mfojtik as group lead should be in approver list

Add mfojtik as approver

---

.dockerignore

Fixes local image build failure with imagebuilder https://github.com/openshift/imagebuilder/issues/140
/cc @sallyom

Fix local image build

---

OWNERS

Add soltysh to approvers

---

go.mod
go.sum
pkg/cmd/render/render.go
vendor/github.com/openshift/library-go/pkg/operator/render/options/config.go
vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
vendor/modules.txt

Bump library go

---

Dockerfile.rhel7

Bug 1856763: update golang version to be 1.13

---

empty-resources/0000_05_config-operator_02_apiserver.cr.yaml
empty-resources/0000_05_config-operator_02_authentication.cr.yaml
empty-resources/0000_05_config-operator_02_build.cr.yaml
empty-resources/0000_05_config-operator_02_console.cr.yaml
empty-resources/0000_05_config-operator_02_dns.cr.yaml
empty-resources/0000_05_config-operator_02_featuregate.cr.yaml
empty-resources/0000_05_config-operator_02_image.cr.yaml
empty-resources/0000_05_config-operator_02_infrastructure.cr.yaml
empty-resources/0000_05_config-operator_02_ingress.cr.yaml
empty-resources/0000_05_config-operator_02_network.cr.yaml
empty-resources/0000_05_config-operator_02_oauth.cr.yaml
empty-resources/0000_05_config-operator_02_operatorhub.cr.yaml
empty-resources/0000_05_config-operator_02_project.cr.yaml
empty-resources/0000_05_config-operator_02_proxy.cr.yaml
empty-resources/0000_05_config-operator_02_scheduler.cr.yaml

This is matches openshift/enhancements#510 and doesn't change existing behavior

add current profile annotations to CVO manifests

---

go.mod
go.sum
vendor/github.com/openshift/api/Dockerfile.build
vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
vendor/github.com/openshift/api/config/v1/types_infrastructure.go
vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
vendor/github.com/openshift/api/operator/v1/types_cloudcredential.go
vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
vendor/github.com/openshift/api/project/v1/generated.proto
vendor/github.com/openshift/api/project/v1/types.go
vendor/github.com/openshift/api/project/v1/zz_generated.swagger_doc_generated.go
vendor/modules.txt

Infrastructure
Signed-off-by: Ravid Brown <ravid@redhat.com>

bump openshift/api to support new field controlPlaneToplogy in

---

go.mod
go.sum
vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
vendor/github.com/openshift/api/operator/v1/types_kubecontrollermanager.go
vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
vendor/modules.txt

pick up https://github.com/openshift/api/pull/966

bump: get updated operator API content

---

cmd/cluster-config-operator/main.go
vendor/k8s.io/component-base/cli/OWNERS
vendor/k8s.io/component-base/cli/run.go
vendor/modules.txt

updated to use component-base/cli
component-base/cli addresses appending logging flags to command line

Bug 2043709: fix component-base logging flags

---

.ci-operator.yaml
Dockerfile.rhel7
go.mod
go.sum

Replaces https://github.com/openshift/cluster-config-operator/pull/232

Update images to be consistent with ART

---

manifests/0000_30_config-operator_01_operator.cr.yaml

This reverts commit 2524b12ae7db1849257c32370dc7af1e0d5f13b8.
cc: @ingvagabund

OCPBUGS-4207: Revert "Increase verbosity level to track probe timeouts"

---

.ci-operator.yaml
Dockerfile.rhel7
go.mod

Signed-off-by: Vu Dinh <vudinh@outlook.com>

OCPBUGS-6185: Update go version and ART images

---

go.mod
go.sum
pkg/cmd/render/render.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/hardcoded_featuregate_reader.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/simple_featuregate_reader.go
vendor/github.com/openshift/library-go/pkg/operator/render/options/config.go
vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/generic.go
vendor/modules.txt

update render to handle directories of manifests

---

pkg/cmd/render/render.go

The manifest directory is used instead.
/hold
holding until hypershift and @sjenning are ready.
/assign @JoelSpeed

remove dead flag for file

---

go.mod
go.sum
vendor/github.com/openshift/api/config/v1/types_feature.go
vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset.crd.yaml
vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
vendor/modules.txt

This reverts commit a6e6a81d992d47e22b4c50d1c22d3e824fd72229.

Revert "Bump to enable ValidatingAdmissionPolicy in tech preview."

---

go.mod
go.sum
vendor/github.com/openshift/api/config/v1/feature_gates.go
vendor/github.com/openshift/api/config/v1/types_feature.go
vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
vendor/github.com/openshift/api/operator/v1/stable.ingresscontroller.testsuite.yaml
vendor/github.com/openshift/api/operator/v1/types_ingress.go
vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
vendor/modules.txt

Pull latest changes from api repo including removing AdmissionWebhookMatchConditions feature gate

Remove AdmissionWebhookMatchConditions feature gate

---

pkg/cmd/render/config.go

The last consumer was removed in d1874f8b2f (#309).

NO-JIRA: pkg/cmd/render/config: Remove ReadFeatureGateV1OrDie

---

manifests/0000_10_config-operator_08_clusteroperator.yaml
pkg/cmd/render/render.go

/assign @JoelSpeed 
This will allow https://github.com/openshift/installer/pull/7666 to test cleanly

Allow split rendering between cluster-config and openshift/api

---

pkg/cmd/render/render.go

found workign through https://github.com/openshift/installer/pull/7666/files

create parent dir for output

---

go.mod
go.sum
vendor/github.com/openshift/api/config/v1/feature_gates.go
vendor/github.com/openshift/api/config/v1/types_feature.go
vendor/modules.txt

CNF-10479:Bump up api to pull mixed cpu allocation feature gate

---

manifests/0000_10_config-operator_07_deployment.yaml
manifests/image-references
pkg/cmd/operator/cmd.go
pkg/cmd/render/config.go
pkg/operator/featuregates/featuregate_controller.go
pkg/operator/starter.go

https://github.com/openshift/api/pull/1567 is needed first, but this is how it would be used.
/hold until 4.15

read featuregates from openshift/api

---

manifests/0000_50_cluster-config-api_featureGate-Default.yaml
manifests/0000_50_cluster-config-api_featureGate-TechPreviewNoUpgrade.yaml

to inter-operate with https://github.com/openshift/api/pull/1720
/hold
need to see if this faked image location actually works.

NO-JIRA: add inert featuregate files to allow diff against later releases

---

manifests/0000_10_config-operator_01_openshift-config-ns.yaml

#401 adds annotations instead of labels; this PR fixes that.

OCPBUGS-28621: Fix PSa labels

---

manifests/0000_10_config-operator_01_openshift-config-ns.yaml

This is a manual cherry-pick of #401.

[release-4.15] OCPBUGS-28622: Add required PSa labels

---

manifests/0000_10_config-operator_01_openshift-config-ns.yaml

This is a manual cherry pick of #401.
/assign @deads2k

[release-4.13] OCPBUGS-28802: Add required PSa labels

---

pkg/operator/starter.go

This should be a safe first step towards adding clusterprofiles to openshfit/api's payload manifest.
/assign @JoelSpeed

NO-JIRA: add check to ensure clusterprofile matches for featuregates

---

pkg/operator/featuregates/featuregate_controller.go
pkg/operator/featuregates/featuregate_controller_test.go

…ce disable
/assign @JoelSpeed

NO-JIRA: change the customnoupgrade featureset to work as force enable and force disable
